const products = [
  {
    id: 1,
    name: 'Joote Zari Red',
    shortName: 'ZARI RED',
    craft: 'Zari',
    origin: 'Surat & Varanasi',
    price: 3960,
    originalPrice: 4960,
    status: 'sale',
    color: '#A62B2B',
    bgGradient: ['#5C1616', '#A62B2B', '#3D0F0F'],
    image: './zari-hero.png',
    link: 'https://wearnaaw.com/product/naaw-zari-red',
    description: "Deep red finish, blending India's textile heritage with contemporary streetwear."
  },
  {
    id: 2,
    name: 'Joote Kantha Olive',
    shortName: 'KANTHA OLIVE',
    craft: 'Kantha',
    origin: 'Bengal, East India',
    price: 3900,
    originalPrice: 4880,
    status: 'sale',
    color: '#6E7B3F',
    bgGradient: ['#3A4020', '#6E7B3F', '#2A2E18'],
    image: './kantha-olive.png',
    heroScale: 0.75,
    link: 'https://wearnaaw.com/product/naaw-kantha-zari-olive-green',
    description: 'Premium textile panel with traditional Kantha stitching in olive green.'
  },
  {
    id: 3,
    name: 'Joote Kantha Tan',
    shortName: 'KANTHA TAN',
    craft: 'Kantha',
    origin: 'Bengal, East India',
    price: 3900,
    originalPrice: 4880,
    status: 'sale',
    color: '#966B42',
    bgGradient: ['#503822', '#966B42', '#3A2815'],
    image: './kantha-tan.png',
    link: 'https://wearnaaw.com/product/naaw-kantha-zari-tan',
    description: 'Heritage Kantha embroidery on a clean streetwear silhouette.'
  },
  {
    id: 4,
    name: 'Joote Kantha Blue',
    shortName: 'KANTHA BLUE',
    craft: 'Kantha',
    origin: 'Bengal, East India',
    price: 3900,
    originalPrice: 4880,
    status: 'sale',
    color: '#2C4E7E',
    bgGradient: ['#162840', '#2C4E7E', '#0F1D30'],
    image: './kantha-blue-clean.png',
    link: 'https://wearnaaw.com/product/naaw-kantha-zari',
    description: 'Hand-inspired Kantha embroidery across a premium textile upper.'
  },
  {
    id: 5,
    name: 'Joote Zari Denim',
    shortName: 'ZARI DENIM',
    craft: 'Zari',
    origin: 'Surat & Varanasi',
    price: 3960,
    originalPrice: 4960,
    status: 'sale',
    color: '#3E5F82',
    bgGradient: ['#1E3048', '#3E5F82', '#152230'],
    image: 'https://wearnaaw.com/storage/2026/07/IMG_7107.png',
    link: 'https://wearnaaw.com/product/naaw-zari-denim',
    description: 'Denim-blue finish with intricate Zari threadwork, built for everyday comfort.'
  },
  {
    id: 6,
    name: 'Joote Zari Mocha',
    shortName: 'ZARI MOCHA',
    craft: 'Zari',
    origin: 'Surat & Varanasi',
    price: 3960,
    originalPrice: 4960,
    status: 'sale',
    color: '#7A5842',
    bgGradient: ['#3E2C20', '#7A5842', '#2D1F16'],
    image: './zari-mocha-v3.jpg',
    link: 'https://wearnaaw.com/product/naaw-zari-noir',
    description: 'Warm mocha finish with premium texture and golden Zari detailing.'
  },
  {
    id: 7,
    name: 'Joote Kantha Chocolate',
    shortName: 'KANTHA CHOCO',
    craft: 'Kantha',
    origin: 'Bengal, East India',
    price: 3900,
    originalPrice: null,
    status: 'coming',
    color: '#5B3A24',
    bgGradient: ['#2E1C10', '#5B3A24', '#1F120A'],
    image: 'https://wearnaaw.com/storage/2026/06/IMG_6791.png',
    link: 'https://wearnaaw.com/product/naaw-kantha-zari-chocolate-brown',
    description: 'Traditional Kantha stitchwork on a modern streetwear silhouette.'
  },
  {
    id: 8,
    name: 'Joote Chikenkadi Purple',
    shortName: 'CHIKENKADI',
    craft: 'Chikankari',
    origin: 'Lucknow, Uttar Pradesh',
    price: 3900,
    originalPrice: null,
    status: 'coming',
    color: '#5A3A7E',
    bgGradient: ['#2D1C40', '#5A3A7E', '#1E1230'],
    image: 'https://wearnaaw.com/storage/2026/06/IMG_6255.JPG.jpeg',
    link: 'https://wearnaaw.com/product/naaw-chikenkadi-purple',
    description: 'Inspired by Chikankari, the timeless embroidery craft of Lucknow.'
  },
  {
    id: 9,
    name: 'Joote ROOH',
    shortName: 'ROOH',
    craft: 'Heritage',
    origin: 'India',
    price: 4200,
    originalPrice: null,
    status: 'coming',
    color: '#A08B6A',
    bgGradient: ['#504535', '#A08B6A', '#3A3228'],
    image: 'https://wearnaaw.com/storage/2026/06/IMG_6830.png',
    link: 'https://wearnaaw.com/product/naaw-rooh',
    description: 'Built on soul and detail, in premium materials with heritage-inspired craft.'
  },
  {
    id: 10,
    name: 'Joote NEELKANTH',
    shortName: 'NEELKANTH',
    craft: 'Indigo',
    origin: 'India',
    price: 4200,
    originalPrice: null,
    status: 'coming',
    color: '#1F2846',
    bgGradient: ['#0F1525', '#1F2846', '#0A0E1A'],
    image: 'https://wearnaaw.com/storage/2026/07/42.png',
    link: 'https://wearnaaw.com/product/naaw-neelkanth',
    description: 'Indigo-inspired handcrafted Indian sneakers in premium suede.'
  }
];
